/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameFons.java
 *
 * Created on 30-abr-2010, 12:43:27
 */

package juegoblackjack;

import CompartidoClientes.Tcom;
import java.awt.Image;
/**
 *
 * @author georgina.punsoda
 */
public class FrameFons extends javax.swing.JFrame {

    private final PanelFons contenedor = new PanelFons();
    /** Creates new form FrameFons */
    public FrameFons() {
        initComponents();
        setContentPane(contenedor);
        setImagen("interf.jpg");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1459, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFons().setVisible(true);
            }
        });
    }

    /*Funcio que escriu el nom dels jugadors de la taula*/
    public void setNoms(int num, int pos, String noms[]){
        contenedor.setNoms(num, pos, noms);
    }

    /*Funcio que es crida per a carregar la imatge del fons*/
    public void setImagen(String nom) {
        contenedor.setImagen(nom);
    }

    public void tratarInfo(Tcom info){
        contenedor.tratarInfo(info);
    }

    public void setImagen(Image im) {
        contenedor.setImagen(im);
    }

    public void setDivide(){
        contenedor.divide();
    }

    public void setDivide2(){
        contenedor.divide2();
    }

    public void setNoDivide(){
        contenedor.noDivide();
    }

    public void reset(){
        contenedor.reset();
    }

    public void noReset(){
        contenedor.noReset();
    }

    public void perdut(Tcom ant){
        contenedor.perdut(ant);
    }

    public void guanyat(Tcom ant){
        contenedor.guanyat(ant);
    }

    public void empat(Tcom ant){
        contenedor.empat(ant);
    }

    public void borrarPuntet(){
        contenedor.borrarPuntet();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
