/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menuJuego.java
 *
 * Created on 27-abr-2010, 9:38:38
 */

package juegoblackjack;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import CompartidoClientes.*;
//import servidor.Mesa;

/**
 *
 * @author marc.sitges
 */
public class menuJuego extends javax.swing.JFrame {

    /** Creates new form menuJuego */
    private String Alias;
    private String pass;
    private socketUsuario sU;
    ArrayList<Mesa> listaMesas;

    public menuJuego() {
        initComponents();
    }

    public menuJuego(String alias, String password) throws IOException {
        initComponents();

        Alias = alias;
        pass = password;
        sU = null;
        sU = new socketUsuario();
        /* CARGAR USUARIO */

        /* CARGAR PARTIDAS */
        try {
            sU.avisarAccion("6"); //cargar mesas
        } catch (IOException ex) {
            Logger.getLogger(menuJuego.class.getName()).log(Level.SEVERE, null, ex);
        }

        listaMesas = sU.obtenerMesas(); //cargar mesas

        cargarMesas();


    }

    private void cargarMesas() {

        int N = listaMesas.size();
        String[] listData = new String[N];
        String mesa;
       // DefaultListModel model = new DefaultListModel();
       // jList1 = new JList(model);
        for(int i=0;i<N;i++)
        {
            mesa = "Mesa "+(listaMesas.get(i).getIdMesa()+1)+" Num jugadores:"+listaMesas.get(i).getNumJugadores();
            listData[i]=mesa;
            jList1.setListData(listData);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Juego");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Hola","Adeu"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("MENU DE JUEGO");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        /** ACCIONES
         *
         * Crear jugador (hecho)
         * Unirse a la partida
         * 
         **/
            sU = new socketUsuario();

            int idm = jList1.getSelectedIndex();
   
        try {
            sU.avisarAccion("2");
        } catch (IOException ex) {
            Logger.getLogger(menuJuego.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sU.crearJugador(Alias,idm);
        } catch (IOException ex) {
            Logger.getLogger(menuJuego.class.getName()).log(Level.SEVERE, null, ex);
        }


        String val = (String) jList1.getSelectedValue();
        System.out.println(val);
//        Tjugada jug= new Tjugada(idm, Alias);
//        jug.setAccion(CONSTANTES.ENTRARENJEGO);
//        this.sendJugada(jug);

        /*idMesa=0*/
        Images fr= new Images(Alias, idm);
        System.out.println("QUE HEXITOSO!!!");
        fr.setVisible(true);
        this.setVisible(false);
        Integer to= 5;
       // to.


    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendJugada(Tjugada tj){
        try {
            sU.avisarAccion("5");
        } catch (IOException ex) {
            Logger.getLogger(Images.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sU.enviarJugada(tj);
        } catch (IOException ex) {

        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
